sudo: required
services:
  - docker

before_install:
  - docker build -t ubersensei/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ubersensei/react-test npm test -- --coverage

after_success:
  - docker build -t ubersensei/unstable-client ./client
  - docker build -t ubersensei/unstable-nginx ./nginx
  - docker build -t ubersensei/unstable-server ./server
  # Login to Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ubersensei/unstable-client 
  - docker push ubersensei/unstable-nginx 
  - docker push ubersensei/unstable-server 

# deploy:
#   provider: elasticbeanstalk
#   region: us-west-2
#   app: unstable-docker
#   env: UnstableDocker-env
#   bucket_name: elasticbeanstalk-us-west-2-922767242623
#   bucket_path: docker-unstable
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#       secure: $AWS_SECRET_KEY
