version: '3.6'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  mariadb:
    image: 'mariadb:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=tangent90
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - RDS_HOSTNAME=mariadb
      - RDS_USERNAME=root
      - RDS_PASSWORD=tangent90
      - RDS_DATABASE=slingshot_db
      - RDS_PORT=3306
      - WAIT_HOSTS="mariadb:3306"
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
        - /app/node_modules
        - ./client:/app     